---
title: RNews - 2017-12-12
author: ~
date: '2017-12-12'
slug: rnews-2017-12-12
categories: []
tags: []
---

This list is quite small because I hit the history limit on Twitter:( Nevertheless, there are some exciting things - e.g. videos from H2O World 2017.

### Videos

- https://www.youtube.com/playlist?list=PLNtMya54qvOHQs2ZmV-pPSW_etMUykE0_ - list of all videos from `H2O World 2017`. There are at least a few videos which seem to be worth watching. Unfortunately, I didn't have time to do so:(.

### Articles:

- https://rviews.rstudio.com/2017/12/11/r-and-tensorflow/ - this article claims that installing `keras` (for deep learning) is as simple as calling `keras::install_keras()`. I hope that's true;)

- https://r-posts.com/leveraging-pipeline-in-spark-trough-scala-and-sparklyr/ - a short comparison of some Spark code written in Scala, and R. Personally, I think that when it comes to working with Spark Scala is a better tool, because you don't always have nicely structured data ready to put into ML algorithm. Sometimes you need to have more control over underlying data structures, and this cannot be achieved using `sparklyr` - not everything can be done using dplyr's style operations.
